/**
 * 作品集页面配置文件
 * 包含作品项目配置
 */

/**
 * 作品集页面配置文件
 * 包含作品项目配置
 * 
 * 图片路径说明：
 * - image: 预览图路径，相对于 public 目录
 * - 所有预览图统一为 16:10 WebP，避免卡片因素材比例不同而跳动
 */

export const portfolioImages = {
  citeai: '/images/portfolio/citeai.webp',
  gworkspace: '/images/portfolio/gworkspace.webp',
  oceannect: '/images/portfolio/oceannect.webp',
  vana: '/images/portfolio/vana.webp',
  farivy: '/images/portfolio/farivy.webp',
  oceanseo: '/images/portfolio/oceanseo.webp',
  moblify: '/images/portfolio/moblify.webp',
  'personal-resume': '/images/portfolio/personal-resume.webp',
  surfsmart: '/images/portfolio/surfsmart.webp',
  'twilight-zone': '/images/portfolio/twilight-zone.webp',
  'portfolio-site': '/images/portfolio/portfolio-site.webp',
}

export const portfolioConfig = [
  { 
    slug: 'citeai',
    titleKey: 'portfolio.items.citeAI.title',
    descKey: 'portfolio.items.citeAI.desc',
    roleKey: 'portfolio.items.citeAI.role',
    highlightKeys: ['portfolio.items.citeAI.highlight1', 'portfolio.items.citeAI.highlight2'],
    start: '2026-01',
    end: '2026-05',
    url: 'https://citeai.co',
    tags: ['Commercial SaaS', 'AI Retrieval', 'Payments'],
    technologies: ['Next.js', 'Supabase', 'FastAPI', 'AWS Lambda', 'Stripe'],
    iconName: 'BrainIcon',
    image: portfolioImages.citeai,
    featured: true,
  },
  {
    slug: 'gworkspace',
    titleKey: 'portfolio.items.glassDashboard.title',
    descKey: 'portfolio.items.glassDashboard.desc',
    roleKey: 'portfolio.items.glassDashboard.role',
    highlightKeys: ['portfolio.items.glassDashboard.highlight1', 'portfolio.items.glassDashboard.highlight2'],
    start: '2025-12',
    end: null,
    url: '/workspace',
    tags: ['Full-stack', 'Content API', '3D Web'],
    technologies: ['Vue 3', 'Express', 'SQLite', 'Next.js', 'Three.js'],
    iconName: 'LayoutIcon', 
    image: portfolioImages.gworkspace,
    featured: true,
  },
  {
    slug: 'oceannect',
    titleKey: 'portfolio.items.oceannect.title',
    descKey: 'portfolio.items.oceannect.desc',
    roleKey: 'portfolio.items.oceannect.role',
    highlightKeys: ['portfolio.items.oceannect.highlight1', 'portfolio.items.oceannect.highlight2'],
    start: '2026-07',
    end: null,
    url: 'https://oceannect.gellaronline.cc',
    tags: ['Mobile', 'Private Sharing', 'Production Ops'],
    technologies: ['Flutter', 'Dart', 'FastAPI', 'SQLAlchemy', 'PostgreSQL', 'Docker'],
    iconName: 'CompassIcon',
    image: portfolioImages.oceannect,
    featured: true,
  },
  {
    slug: 'vana',
    titleKey: 'portfolio.items.vana.title',
    descKey: 'portfolio.items.vana.desc',
    roleKey: 'portfolio.items.vana.role',
    highlightKeys: ['portfolio.items.vana.highlight1', 'portfolio.items.vana.highlight2'],
    start: '2026-01',
    end: null,
    url: 'https://github.com/oneder2/Vana',
    tags: ['Local-first', 'Desktop', 'Sync'],
    technologies: ['Tauri v2', 'Rust', 'React', 'SQLite', 'Supabase'],
    iconName: 'FileTextIcon',
    image: portfolioImages.vana,
    featured: true,
  },
  {
    slug: 'farivy',
    titleKey: 'portfolio.items.farivy.title',
    descKey: 'portfolio.items.farivy.desc',
    roleKey: 'portfolio.items.farivy.role',
    highlightKeys: ['portfolio.items.farivy.highlight1', 'portfolio.items.farivy.highlight2'],
    start: '2026-03',
    end: null,
    url: 'https://github.com/oneder2/Farivy',
    tags: ['Mobile', 'Local-first', 'Analytics'],
    technologies: ['Flutter', 'Dart', 'Riverpod', 'SQLite'],
    iconName: 'StopwatchIcon',
    image: portfolioImages.farivy,
    featured: true,
  },
  {
    slug: 'oceanseo',
    titleKey: 'portfolio.items.oceanseo.title',
    descKey: 'portfolio.items.oceanseo.desc',
    roleKey: 'portfolio.items.oceanseo.role',
    highlightKeys: ['portfolio.items.oceanseo.highlight1', 'portfolio.items.oceanseo.highlight2'],
    start: '2026-09',
    end: null,
    url: 'https://github.com/oneder2/Oceanseo',
    tags: ['Desktop', 'Automation', 'AI Workflow'],
    technologies: ['Tauri v2', 'Rust', 'React', 'SQLite'],
    iconName: 'ClockIcon',
    image: portfolioImages.oceanseo,
    featured: true,
  },
  {
    slug: 'moblify',
    titleKey: 'portfolio.items.moblify.title',
    descKey: 'portfolio.items.moblify.desc',
    roleKey: 'portfolio.items.moblify.role',
    highlightKeys: ['portfolio.items.moblify.highlight1', 'portfolio.items.moblify.highlight2'],
    start: '2026-03',
    end: '2026-03',
    url: 'https://github.com/oneder2/symmetrical-octo-invention',
    tags: ['Automation', 'Video', 'Scoring'],
    technologies: ['Python', 'FastAPI', 'Next.js', 'OpenCV', 'FFmpeg'],
    iconName: 'YouTubeIcon',
    image: portfolioImages.moblify,
    featured: true,
  },
  {
    slug: 'personal-resume',
    titleKey: 'portfolio.items.personalResume.title',
    descKey: 'portfolio.items.personalResume.desc',
    roleKey: 'portfolio.items.personalResume.role',
    highlightKeys: [],
    start: '2024-12',
    end: null,
    url: 'https://resume.gellaronline.cc',
    tags: ['Resume', 'Publishing'],
    technologies: ['HTML5', 'CSS3', 'JavaScript', 'GitHub Pages', 'LaTeX'],
    iconName: 'FileTextIcon',
    image: portfolioImages['personal-resume'],
    featured: false,
  },
  {
    slug: 'surfsmart',
    titleKey: 'portfolio.items.surfsmart.title',
    descKey: 'portfolio.items.surfsmart.desc',
    roleKey: 'portfolio.items.surfsmart.role',
    highlightKeys: [],
    start: '2025-04',
    end: '2025-04',
    url: '/portfolio/surfsmart',
    tags: ['Hackathon', 'AI Research'],
    technologies: ['Python', 'SQL', 'React', 'Flask', 'MongoDB', 'LangChain'],
    iconName: 'BrainIcon',
    image: portfolioImages.surfsmart,
    featured: false,
  },
  {
    slug: 'twilight-zone',
    titleKey: 'portfolio.items.twilightZone.title',
    descKey: 'portfolio.items.twilightZone.desc',
    roleKey: 'portfolio.items.twilightZone.role',
    highlightKeys: [],
    start: '2025-02',
    end: '2025-02',
    url: 'https://github.com/oneder2/twilight-zone',
    tags: ['Game', 'Narrative'],
    technologies: ['C#', 'Unity', 'Aseprite', 'Krita', 'BeepBox'],
    iconName: 'CodeIcon',
    image: portfolioImages['twilight-zone'],
    featured: false,
  },
  {
    slug: 'portfolio-site',
    titleKey: 'portfolio.items.portfolioSite.title',
    descKey: 'portfolio.items.portfolioSite.desc',
    roleKey: 'portfolio.items.portfolioSite.role',
    highlightKeys: [],
    start: '2026-08',
    end: null,
    url: 'https://portfolio.gellaronline.cc',
    tags: ['Web', 'Portfolio'],
    technologies: ['Web', 'Portfolio'],
    iconName: 'LayoutIcon',
    image: portfolioImages['portfolio-site'],
    featured: false,
  },
]
